line-length = 100

[format]
quote-style = "double"
indent-style = "space"

[lint]
extend-select = ["B", "E", "ERA", "F", "I", "N", "PT", "PYI", "RET", "RUF", "SIM", "UP", "W"]
extend-ignore = ["E501", "F811", "PT011", "PT012", "PT013", "PYI041", "RET504", "SIM118"]
extend-unfixable = ["B905"]

[lint.isort]
force-sort-within-sections = true

[lint.flake8-pytest-style]
parametrize-names-type = "csv"
